video_path: /root/CLEVAM-DM/input/example.mp4 # path/to/video
keyframe_path: /root/CLEVAM-DM/input/keyframes/ # path/to/keyframes
frame_path: /root/CLEVAM-DM/input/frames/ # path/to/frames
output_dir: /root/CLEVAM-DM/video_output/example/ # path/to/output
maskformer_path: /root/CLEVAM-DM/src/mask_former/configs/maskformer_R50_bs32_60k.yaml
brushnet_path: /root/CLEVAM-DM/data/ckpt
num_inference_steps: 50
interval: 24 # interval between frames, 70 for 4 images
prompts:
  original_inside: skiing person in the front
  edit_inside: skiing polar bear
  original_outside: background
  edit_outside: background

guidance_scale: 3.5
chunk_size: 18

optical_flow:
  model_name: dpflow
  ckpt_path: sintel

device: cuda

